version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - control

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - control

  keycloak:
    image: mohammedamineraziq/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    networks:
      - control

  eureka-server:
    image: mohammedamineraziq/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    networks:
      - control

  gateway-server:
    image: mohammedamineraziq/gateway-server
    container_name: gateway-server
    ports:
      - "8889:8889"
    environment:
      EUREKA_SERVER_ADDRESS: http://eureka-server:8761/eureka/
      KEYCLOAK_REALM: my-ecom-realm
      KEYCLOAK_CLIENT: ecom-app
      KEYCLOAK_ADDRESS: http://host.docker.internal:8080
    depends_on:
      - eureka-server
      - keycloak
    networks:
      - control

  customer-server:
    image: mohammedamineraziq/customer-server
    container_name: customer-server
    ports:
      - "8081:8081"
    environment:
      EUREKA_SERVER_ADDRESS: http://eureka-server:8761/eureka/
      BROKER_ADDRESS: broker:29092
      KEYCLOAK_REALM: my-ecom-realm
      KEYCLOAK_CLIENT: ecom-app
      KEYCLOAK_ADDRESS: http://host.docker.internal:8080
    depends_on:
      - eureka-server
      - keycloak
    networks:
      - control

  inventory-server:
    image: mohammedamineraziq/inventory-server
    container_name: inventory-server
    ports:
      - "8082:8082"
    environment:
      EUREKA_SERVER_ADDRESS: http://eureka-server:8761/eureka/
      BROKER_ADDRESS: broker:29092
      KEYCLOAK_REALM: my-ecom-realm
      KEYCLOAK_CLIENT: ecom-app
      KEYCLOAK_ADDRESS: http://host.docker.internal:8080
    depends_on:
      - eureka-server
      - keycloak

    networks:
      - control

  billing-server:
    image: mohammedamineraziq/billing-server
    container_name: billing-server
    ports:
      - "8083:8083"
    environment:
      EUREKA_SERVER_ADDRESS: http://eureka-server:8761/eureka/
      BROKER_ADDRESS: broker:29092
      KEYCLOAK_REALM: my-ecom-realm
      KEYCLOAK_CLIENT: ecom-app
      KEYCLOAK_ADDRESS: http://host.docker.internal:8080
    depends_on:
      - eureka-server
      - customer-server
      - inventory-server
      - zookeeper
      - broker
      - keycloak
    networks:
      - control

  randomorder-server:
    image: mohammedamineraziq/randomorder-server
    container_name: randomorder-server
    ports:
      - "8084:8084"
    environment:
      EUREKA_SERVER_ADDRESS: http://eureka-server:8761/eureka/
      BROKER_ADDRESS: broker:29092
      KEYCLOAK_REALM: my-ecom-realm
      KEYCLOAK_CLIENT: ecom-app
      KEYCLOAK_ADDRESS: http://host.docker.internal:8080
    depends_on:
      - eureka-server
      - zookeeper
      - broker
      - customer-server
      - inventory-server
      - keycloak
    networks:
      - control

  analytics-server:
    image: mohammedamineraziq/analytics-server
    container_name: analytics-server
    ports:
      - "8086:8086"
    environment:
      EUREKA_SERVER_ADDRESS: http://eureka-server:8761/eureka/
      BROKER_ADDRESS: broker:29092
      KEYCLOAK_REALM: my-ecom-realm
      KEYCLOAK_CLIENT: ecom-app
      KEYCLOAK_ADDRESS: http://host.docker.internal:8080
    depends_on:
      - eureka-server
      - zookeeper
      - broker
      - keycloak
    networks:
      - control

networks:
  control:
